version: '3.5'
services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php.p2p.local
        volumes:
        -   .:/var/www/html
        working_dir: /var/www/html

    nginx:
        image: nginx
        container_name: nginx.p2p.local
        volumes:
        -   .:/var/www/html
        -   ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
        -   8191:80
        depends_on:
        -   php

    mysql:
        image: mysql
        container_name: mysql.p2p.local
        environment:
            MYSQL_ROOT_PASSWORD: p2p
            MYSQL_DATABASE: p2p
        volumes:
        -   ./var/docker/mysql:/var/lib/mysql